#!/usr/bin/env bash

COM="${HOME}/.config/xmobar/com/weather"
[[ -n "$1" ]] && STATE_FILE="${HOME}/.config/xmobar/scripts/state" && source "${STATE_FILE}"
source "${HOME}/.config/xmobar/scripts/page/index" 2

now=$(date +%s)

source "${HOME}/.config/xmobar/scripts/state_loader"
state_init "weather_value" ""
state_init "weather_timestamp" $((now - 3601))
state_init "weather_loading_live" 0
state_init "weather_spinner" 0

case "$1" in
  run) ${COM}/actions/run             \
    --STATE_FILE=${STATE_FILE}        \
    --TIMESTAMP_KEY=weather_timestamp \
    --VALUE_KEY=weather_value         \
    --LOADING_KEY=weather_loading_live ;;
  *) ;;
esac

if (( weather_loading_live == 1 )); then
  spinner_icons=(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
  idx=$(( ( weather_spinner + 1 ) % ${#spinner_icons[@]} ))
  state_update "weather_spinner" "$idx"
  echo "<fc=${COLOR_INFO}>${spinner_icons[$idx]} Update...󱣶 </fc>"
  exit 0
fi

echo "<fc=${COLOR_WHITE}>${weather_value}</fc>"
