#!/usr/bin/env bash
# xbps-install libspa-bluetooth -- bluetooth support for audio

source "${HOME}/.config/barlib/scripts/env"
COM="${BAR_COMPONENTS_DIR}/com/volume"
[[ -n "$1" ]] && source "${STATE_FILE}"
source "${BAR_COMPONENTS_DIR}/scripts/page/index" 1

source "${BAR_COMPONENTS_DIR}/scripts/cache"
source "${BAR_COMPONENTS_DIR}/scripts/tuples"

STEP=3
MAX_VOLUME=125
ICON_MUTED=""
default_sink="@DEFAULT_AUDIO_SINK@"

get_volume() {
  wpctl get-volume "${default_sink}" | awk '{printf "%.0f\n", $2 * 100}'
}

is_muted() {
  wpctl get-volume "${default_sink}" | grep -q MUTED && echo 1 || echo 0
}

case "$1" in
  volume_jump) ${COM}/actions/volume_jump \
    --sink=${default_sink} --volume=$(get_volume) --muted=$(is_muted) ;;
  volume_up)   ${COM}/actions/volume_up   \
    --sink=${default_sink} --volume=$(get_volume) --muted=$(is_muted) \
    --step=${STEP} --max_volume=${MAX_VOLUME} ;;
  volume_down) ${COM}/actions/volume_down \
    --sink=${default_sink} --volume=$(get_volume) --step=${STEP} ;;
  mute)        ${COM}/actions/mute        \
    --sink=${default_sink} --volume=$(get_volume) ;;
  *) ;;
esac

if ! cache_cmd "wireplumber_check" 3 pgrep -x wireplumber >/dev/null 2>&1; then
  emit_tuple 0 "$COLOR_DANGER" "  󰖁"
  emit_sep "󰜥"
  exit 0
fi

if (( $(is_muted) == 1 )); then
  emit_tuple 0 "$COLOR_MUTE" "$ICON_MUTED"
  emit_sep "󰜥"
  exit 0
fi

vol=$(get_volume)

thresholds=(0 20 40 75)
sound_icons=("" "" "" "󰕾" "")
sound_icon="${sound_icons[-1]}"
for i in "${!thresholds[@]}"; do
  if (( vol <= thresholds[i] )); then
    sound_icon="${sound_icons[$i]}"
    break
  fi
done

color=$([[ $vol -gt 100 ]] && echo "$COLOR_DANGER" || echo "$COLOR_WHITE")
emit_tuple 0 "$color" "$sound_icon  $vol󰏰"
emit_sep "󰜥"
