#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

source "${HOME}/.config/xmobar/scripts/terminal_launcher"

terminal_launch \
  --title "Disk Usage" \
  --command "dysk" \
  --class "float-small" \
  --hold
