#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"

COM="${HOME}/.config/xmobar/com/updates"
VALUE_FILE="${COM}/state/value"

WARNING_COUNT=15

CACHE_TTL=3600 #one hour


now=$(date +%s)
if [[ -f "$VALUE_FILE" ]]; then
  read -r cached_ts < "$VALUE_FILE"
else
  cached_ts=0
fi

# Refresh cache if older than 1 minute
if (( now - cached_ts >= CACHE_TTL )); then
  package_list=$(xbps-install -nuM)
  count="$(printf "%s\n" "$package_list" | grep -cve '^\s*$')"
  {
    echo "$now"
    echo "$count"
  } > "$VALUE_FILE"
else
  count="$(sed -n '2p' "$VALUE_FILE")"
fi

(( count == 0 )) && exit 0

case "$1" in
    show) ${COM}/actions/show --package_list=${package_list} --VALUE_FILE=${VALUE_FILE} ;;
    *) ;;
esac

output="  $count"

if (( count >= WARNING_COUNT )); then
    echo "<fc=${COLOR_WARNING}>${output}</fc>${SEP}"
else
    echo "$output ${SEP}"
fi
