#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/page/index"

interface=wlan0
lan_interface=eth0
wifi_name_length=150

spinner_icons=(      )

COM="${HOME}/.config/xmobar/com/network"
LOADING_FILE="${COM}/state/loading"
SPINNER_FILE="${COM}/state/spinner"
ENABLED_FILE="${COM}/state/enabled"

if [ ! -f "$LOADING_FILE" ]; then
  echo 0 > "$LOADING_FILE"
fi

if [ ! -f "$ENABLED_FILE" ]; then
  echo 1 > "$ENABLED_FILE"
fi

is_loading=$(cat "$LOADING_FILE")
is_enabled=$(cat "$ENABLED_FILE")

if (( is_loading == 1 )); then
  idx=$(cat "$SPINNER_FILE")
  idx=$(( (idx + 1) % ${#spinner_icons[@]} ))
  echo "$idx" > "$SPINNER_FILE"
fi

spinner_idx=$(cat "$SPINNER_FILE")
spinner=${spinner_icons[$spinner_idx]}

for iface in $(ip -o link show | awk -F': ' '{print $2}'); do
    if [ -d "/sys/class/net/$iface/wireless" ]; then
        interface=$iface
        break
    fi
done

for iface in $(ip -o link show | awk -F': ' '{print $2}'); do
    if [ ! -d "/sys/class/net/$iface/wireless" ] && [[ $iface != lo ]]; then
        lan_interface=$iface
        break
    fi
done

if ip link show ${lan_interface} | grep -q 'state UP'; then
  echo "LAN<fc=${COLOR_MUTE}> 󰜥 </fc> 󰈀${SEP}"
  exit 0
fi

case "$1" in
  connect)  $HOME/.config/xmobar/com/network/actions/connect       --interface=${interface}  --LOADING_FILE=${LOADING_FILE} ;;
  disconnect)  $HOME/.config/xmobar/com/network/actions/disconnect --interface=${interface}  --ENABLED_FILE=${ENABLED_FILE} --enabled=${enabled} ;;
  *) ;;
esac

if (( is_enabled == 0 )); then
  echo "<fc=${COLOR_MUTE}> Wifi Disabled 󰤮</fc>${SEP}"
  exit 0
fi

ssid=$(wpa_cli -i ${interface} status | awk -F= '/^ssid/ {print $2}')

if [ ${#ssid} -gt ${wifi_name_length} ]; then
  ssid="${ssid:0:$((wifi_name_length-3))}<fc=${COLOR_MUTE}>󰇘</fc>"
fi


signal_icons=( 󰤯 󰤟 󰤢 󰤥 󰤨 )
signal_thresholds=( 15 33 50 90 )
signal_icon=${signal_icons[-1]}
signal=$(awk 'NR==3 {print $3}' /proc/net/wireless | sed 's/\.//')

for i in "${!signal_thresholds[@]}"; do
  if (( signal < signal_thresholds[i] )); then
    signal_icon="${signal_icons[i]}"
    break
  fi
done

if (( is_loading == 0 )); then
  echo "$ssid ${signal}󰏰 ${signal_icon}${SEP}"
fi

if (( is_loading == 1 )); then
  echo "󱛇  ${spinner}${SEP}"
fi
