#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --value=*)       value="${arg#*=}" ;;
    --STATE_FILE=*)  STATE_FILE="${arg#*=}" ;;
    --LOCK_KEY=*)    LOCK_KEY="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

new_value=$(( ! value ))

sed -i "s/^$LOCK_KEY=.*/$LOCK_KEY=${new_value}/" "$STATE_FILE"

[[ $new_value == 1 ]] && notify-send 'Image locked!'
