#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --STATE_FILE=*)        STATE_FILE="${arg#*=}"        ;;
    --TOGGLE_KEY=*)        TOGGLE_KEY="${arg#*=}"        ;;
    --LOADING_KEY=*)       LOADING_KEY="${arg#*=}"       ;;
    --PID_FILE=*)          PID_FILE="${arg#*=}"          ;;
    *) echo "Unknown argument: $arg" ; exit 1            ;;
  esac
done

pid=$(< $PID_FILE)
doas kill -- -${pid} >/dev/null 2>&1
source "${BAR_COMPONENTS_DIR}/scripts/state_loader"

state_update "${TOGGLE_KEY}"  0
state_update "${LOADING_KEY}" 0
rm $PID_FILE

sleep 0.5
"${REFRESH_CMD}"
