#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
source "${BAR_DIR}/scripts/render"

COM="$(resolve_component "volume")"

xmobar_actions "$COM" \
  "1:volume_jump"     \
  "2:mute"            \
  "4:volume_up"       \
  "5:volume_down"
