#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --step=*)    step="${arg#*=}" ;;
    --percent=*) percent="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

brightnessctl set +"${step}"% >/dev/null
echo $percent > "${HOME}/.config/xob/brightness/value"

"${HOME}/.config/xmobar/scripts/refresh"
