#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --VALUE_KEY=*)     VALUE_KEY="${arg#*=}"     ;;
    --TIMESTAMP_KEY=*) TIMESTAMP_KEY="${arg#*=}" ;;
    --STATE_FILE=*)    STATE_FILE="${arg#*=}"    ;;
    --LOADING_KEY=*) LOADING_KEY="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1    ;;
  esac
done

sed -i "s/^$LOADING_KEY=.*/$LOADING_KEY=1/" "$STATE_FILE"

# Run weather update in background
(
  sleep 1
  COM="${HOME}/.config/xmobar/com/weather"
  ${COM}/scripts/runner --STATE_FILE=${STATE_FILE} --TIMESTAMP_KEY=${TIMESTAMP_KEY} --VALUE_KEY=${VALUE_KEY}
  sed -i "s/^$LOADING_KEY=.*/$LOADING_KEY=0/" "$STATE_FILE"
) &
