#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

source "${HOME}/.config/xmobar/scripts/terminal_launcher"

terminal_launch \
  --title "System Monitor" \
  --command "htop" \
  --class "float-large"
