#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/page/index"

COM="${HOME}/.config/xmobar/com/battery"
LEVEL_FILE="${COM}/state/level"
SHOW_TIME_FILE="${COM}/state/show_time"

# If file doesn't exist, start from 0
[[ -f "$LEVEL_FILE" ]] || echo 0 > "$LEVEL_FILE"
[[ -f "$SHOW_TIME_FILE" ]] || echo 0 > "$SHOW_TIME_FILE"

info=$(acpi -b)
state=$(echo "$info" | awk -F'[,: ]+' '{print $3}')
level=$(echo "$info" | awk -F'[,% ]+' '{print $4}')
time=$(echo "$info" | awk '{for(i=1;i<=NF;i++){if($i~/[0-9][0-9]:[0-9][0-9]:[0-9][0-9]/) print $i}}')

thresholds=(10 33 66 85 95)
icons=("󰢟" "󱊤" "󱊥" "󱊦" "󰂅")

showtime=$(cat "$SHOW_TIME_FILE")

if [ "$1" == "show_time" ]; then
  if [[ "$showtime" == 0 ]]; then
      echo 1 > "$SHOW_TIME_FILE"
  else
      echo 0 > "$SHOW_TIME_FILE"
  fi
fi

if [[ "$state" == "Full" ]]; then
  echo "${SEP}"
  exit
fi

if [[ "$state" == "Charging" ]]; then

    usable_icons=()
    for i in "${!thresholds[@]}"; do
        if [[ "$level" -le "${thresholds[$i]}" ]]; then
            usable_icons+=("${icons[$i]}")
        fi
    done

    # Safety fallback
    [[ ${#usable_icons[@]} -eq 0 ]] && usable_icons=("${icons[thresholds[@]-1]}")

    idx=$(cat "$LEVEL_FILE")
    idx=$(( (idx + 1) % ${#usable_icons[@]} ))
    echo "$idx" > "$LEVEL_FILE"

    timercolor=${COLOR_OK}
    icon="${usable_icons[$idx]}  <fc=$timercolor>${level}󰏰</fc>"
    [[ $showtime == 1 ]] && icon="$icon  <fc=$timercolor> $time </fc>"
    echo "${icon}${SEP}"
    exit
fi

# Otherwise output normal code
if [[ "$state" == "Discharging" ]]; then
  thresholds=(10 33 66)
  icons=("󰂎" "󱊡" "󱊢" "󱊣")
  timercolors=($COLOR_CRITIC $COLOR_DANGER $COLOR_WARNING $COLOR_OK)

  icon="${icons[-1]}  ${level}󰏰"
  timercolor=${timercolors[-1]}
  for i in "${!thresholds[@]}"; do
    if (( level < thresholds[i] )); then
      icon="${icons[i]}  ${level}󰏰"
      timercolor=${timercolors[i]}
      break
    fi
  done
else
  icon="󰂃"
fi

[[ $level -le ${thresholds[1]} ]] && output="<fc=$timercolor>$icon</fc>" || output="${icon}"


[[ $showtime == 1 ]] && output="$output <fc=$timercolor> $time </fc>"

echo "${output}${SEP}"
