#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/page/index" 1

COM="${HOME}/.config/xmobar/com/battery"
VALUE_FILE="${COM}/state/value"
3LEVEL_FILE="${COM}/state/level"
SHOW_TIME_FILE="${COM}/state/show_time"

CACHE_TTL=80   # seconds

# If file doesn't exist, start from 0
[[ -f "$LEVEL_FILE"     ]] || echo 0 > "$LEVEL_FILE"
[[ -f "$SHOW_TIME_FILE" ]] || echo 0 > "$SHOW_TIME_FILE"

if ! command -v acpi >/dev/null 2>&1; then
  echo "Warning: acpi is not installed or not in PATH."
  exit 1
fi

now=$(date +%s)
if [[ -f "$VALUE_FILE" ]]; then
  read -r cached_ts < "$VALUE_FILE"
else
  cached_ts=0
fi

# Refresh cache if older than 1 minute
if (( now - cached_ts >= CACHE_TTL )); then
  info="$(acpi -b 2>/dev/null)"
  {
    echo "$now"
    echo "$info"
  } > "$VALUE_FILE"
else
  info="$(sed -n '2p' "$VALUE_FILE")"
fi

# If acpi output does NOT contain "Battery", then exit
echo "$info" | grep -q "Battery" || exit 0

state=$(echo "$info" | awk -F'[,: ]+' '{print $3}')
level=$(echo "$info" | awk -F'[,% ]+' '{print $4}')
time=$(echo "$info"  | awk '{for(i=1;i<=NF;i++){if($i~/[0-9][0-9]:[0-9][0-9]:[0-9][0-9]/) print $i}}')

thresholds=(10 33 66 85 95)
icons=("󰢟" "󱊤" "󱊥" "󱊦" "󰂅")

showtime=$(< "$SHOW_TIME_FILE")

case "$1" in
  show_time) "${COM}/actions/show_time" --showtime=${showtime} --SHOW_TIME_FILE=${SHOW_TIME_FILE} ;;
  *) ;;
esac

if [[ "$state" == "Full" ]]; then
  echo "${SEP}"
  exit 0
fi

if [[ "$state" == "Charging" ]]; then

    usable_icons=()
    for i in "${!thresholds[@]}"; do
        if [[ "$level" -le "${thresholds[$i]}" ]]; then
            usable_icons+=("${icons[$i]}")
        fi
    done

    # Safety fallback
    [[ ${#usable_icons[@]} -eq 0 ]] && usable_icons=("${icons[$((${#icons[@]} - 1))]}")

    idx=$(< "$LEVEL_FILE")
    idx=$(( (idx + 1) % ${#usable_icons[@]} ))
    echo "$idx" > "$LEVEL_FILE"

    timercolor=${COLOR_OK}
    icon="${usable_icons[$idx]}  <fc=$timercolor>${level}󰏰</fc>"
    [[ $showtime == 1 ]] && icon="$icon  <fc=$timercolor> $time </fc>"
    echo "${icon}${SEP}"
    exit
fi

# Otherwise output normal code
if [[ "$state" == "Discharging" ]]; then
  thresholds=(10 33 66)
  icons=("󰂎" "󱊡" "󱊢" "󱊣")
  timercolors=($COLOR_CRITIC $COLOR_DANGER $COLOR_WARNING $COLOR_OK)

  icon="${icons[-1]}  ${level}󰏰"
  timercolor=${timercolors[-1]}
  for i in "${!thresholds[@]}"; do
    if (( level < thresholds[i] )); then
      icon="${icons[i]}  ${level}󰏰"
      timercolor=${timercolors[i]}
      break
    fi
  done
else
  icon="󰂃"
fi

[[ $level -le ${thresholds[1]} ]] && output="<fc=$timercolor>$icon</fc>" || output="${icon}"

[[ $showtime == 1 ]] && output="$output <fc=$timercolor> $time </fc>"

echo "${output}${SEP}"
