#!/usr/bin/env bash
# xbps-install libspa-bluetooth -- bluetooth support for audio

STEP=3  # volume step
MAX_VOLUME=125
ICON_SPEAKER="󰓃"
ICON_HEADPHONES="󰋋"
ICON_BT="<fc=#87c6e6> </fc> 󰋋"
ICON_MUTED=""
OVERFLOW_COLOR="#f58989"
MUTE_COLOR="#696969"

# ------------------------------

default_sink() {
    pactl get-default-sink
}

get_volume() {
  pactl get-sink-volume "$(default_sink)" | awk 'NR==1 {print $5}' | tr -d '%'
}

is_muted() {
    pactl get-sink-mute "$(default_sink)" | grep -q "yes"
}

get_sink_icon() {
    local sink active_port
    sink=$(pactl get-default-sink)
    active_port=$(pactl list sinks | awk -v s="$sink" '
        $0 ~ "Name: "s {found=1}
        found && /Active Port:/ {
            gsub(/.*: /, "", $0)
            print $0
            exit
        }')

    case "$active_port" in
        *speaker* ) echo $ICON_SPEAKER ;;      # speakers
        *headphone* ) echo $ICON_HEADPHONES ;; # wired headphones
        *headset* ) echo $ICON_BT ;;           # headset
        * ) echo -1 ;;                        # fallback
    esac
}

cycle_output_sound() {
    mapfile -t pairs < <(
        pactl list sinks | awk '
            /Name:/ {sink=$2}
            /Ports:/ {show=1; next}
            show==1 && $0 ~ /^[[:space:]]*[a-zA-Z0-9_-]+: / {
                split($1, a, ":")
                print sink " " a[1]
            }
            show==1 && NF==0 {show=0}
        '
    )

    current_port=$(pactl list sinks |
          awk -v tgt="$current_sink" '
              $2 == tgt {found=1}
              found && /Active Port:/ {print $3; exit}
          '
      )

    current_pair="$(default_sink) $current_port"

    next_index=0
    for i in "${!pairs[@]}"; do
        if [[ "${pairs[$i]}" == "$current_pair" ]]; then
            next_index=$(( (i + 1) % ${#pairs[@]} ))
            break
        fi
    done

    next_sink=$(echo "${pairs[$next_index]}" | awk '{print $1}')
    next_port=$(echo "${pairs[$next_index]}" | awk '{print $2}')

    #vol=$(get_volume)
    pactl set-default-sink "$next_sink"
    pactl set-sink-port    "$next_sink" "$next_port"
    #pactl set-sink-volume  "$next_sink" "$(vol)%"
    pactl set-sink-volume  "$next_sink" "40%"
}

volume_jump() {

  if is_muted; then
    pactl set-sink-mute "$(default_sink)" toggle
    pactl set-sink-volume "$(default_sink)" 25%
    return
  fi

  vol=$(get_volume)
  if (( vol < 25 )); then
    pactl set-sink-volume "$(default_sink)" 25%
  elif (( vol < 50 )); then
    pactl set-sink-volume "$(default_sink)" 50%
  elif (( vol < 75 )); then
    pactl set-sink-volume "$(default_sink)" 75%
  elif (( vol < 100 )); then
    pactl set-sink-volume "$(default_sink)" 100%
  else
    pactl set-sink-volume "$(default_sink)" 25%
  fi
}

volume_up() {

  if is_muted; then
    pactl set-sink-mute "$(default_sink)" toggle
  fi

  if (( $(get_volume) >= MAX_VOLUME)); then
    pactl set-sink-volume "$(default_sink)" ${MAX_VOLUME}%
  else
    pactl set-sink-volume "$(default_sink)" +${STEP}%
  fi
}


volume_down() {

  if (( $(get_volume) <= 0 )); then
    pactl set-sink-volume "$(default_sink)" 0%
  else
    pactl set-sink-volume "$(default_sink)" -${STEP}%
  fi
}

mute() {
  pactl set-sink-mute "$(default_sink)" toggle
}

case "$1" in
    volume_jump) volume_jump ;;
    volume_up)   volume_up ;;
    volume_down) volume_down ;;
    toggle)      cycle_output_sound ;;
    mute)        mute ;;
esac


if is_muted; then
  echo "<fc=${MUTE_COLOR}>$ICON_MUTED</fc>"
  exit
fi

icon=$(get_sink_icon)
vol=$(get_volume)

thresholds=(0 20 40 75)
sound_icons=("" "" "" "󰕾" "")

sound_icon="${sound_icons[-1]}"

if (( icon == -1 )); then
  echo "<fc=${OVERFLOW_COLOR}>  󰖁</fc>"
  exit
fi

for i in "${!thresholds[@]}"; do
  if (( vol <= thresholds[i] )); then
    sound_icon="${sound_icons[i]}"
    break
  fi
done

output="$sound_icon  $vol󰏰 <fc=${MUTE_COLOR}>󰜥</fc> $icon"
if (( vol > 100 )); then
  echo "<fc=${OVERFLOW_COLOR}>$output</fc>"
else
  echo "$output"
fi
