#!/usr/bin/env bash

# Vars/state already exported from scripts/bar
source "${HOME}/.config/xmobar/scripts/cache"
source "${HOME}/.config/xmobar/scripts/page/index" 2

if ! command -v sensors >/dev/null 2>&1; then
  echo "Warning: sensors is not installed or not in PATH. (package_name: lm_sensors)"
  exit 1
fi

COM="${HOME}/.config/xmobar/com/cpu_temp"

# Cache sensors output for 3 seconds (temperature doesn't change that fast)
temp=$(cache_cmd "sensors" 3 sensors | awk '/acpitz-acpi-0/ {flag=1} flag && /temp1/ {gsub(/[+°C]/,"",$2); print $2; exit}')
temp_int=${temp%.*}  # Convert to integer for comparison

thresholds=(50 70 85 95)
tempicons=(   "󰈅")
tempcolors=($COLOR_OK $COLOR_WARNING $COLOR_DANGER $COLOR_CRITIC)
tempcolor=${tempcolors[-1]}
tempicon=${tempicons[-1]}

for i in "${!thresholds[@]}"; do
  if (( temp_int < thresholds[i] )); then
    tempcolor=${tempcolors[i]}
    tempicon=${tempicons[i]}
    break
  fi
done

case "$1" in
    top) ${COM}/actions/htop ;;
    *) ;;
esac

echo "<fc=${tempcolor}>${tempicon} ${temp}°</fc>"
