export PATH="$HOME/.local/bin:$PATH"

export XOB_NORMAL_FG_BRIGHTNESS="#f28f2f"
export XOB_NORMAL_BORDER_BRIGHTNESS="#e6c15c"

export XOB_NORMAL_FG_VOLUME="#1E90FF"
export XOB_NORMAL_BORDER_VOLUME="#888888"

export XOB_OF_FG_VOLUME="#FF6347"
export XOB_OF_BORDER_VOLUME="#FF4500"
