#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
source "${BAR_COMPONENTS_DIR}/scripts/vars"

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --VALUE_KEY=*)     VALUE_KEY="${arg#*=}"     ;;
    --COLOR_KEY=*)     COLOR_KEY="${arg#*=}"     ;;
    --TIMESTAMP_KEY=*) TIMESTAMP_KEY="${arg#*=}" ;;
    --STATE_FILE=*)    STATE_FILE="${arg#*=}"    ;;
    *) echo "Unknown argument: $arg" ; exit 1    ;;
  esac
done

now=$(date +%s)

ICON_SUN="󰖙"
ICON_PARTLY="󰖕"
ICON_CLOUD="󰖐"
ICON_RAIN="󰖗"
ICON_DRIZZLE="󰖖"
ICON_SNOW="󰖘"
ICON_STORM="󰙾"
ICON_FOG="󰖑"
ICON_WIND="󰖑"
ICON_UNKNOWN="󰼯"

raw=$(curl -sf "https://wttr.in/?format=%C|%t")

if [[ -z "$raw" ]]; then
  sed -i "s/^$VALUE_KEY=.*/$VALUE_KEY=\"${ICON_UNKNOWN} ?\"/" "$STATE_FILE"
  sed -i "s/^$COLOR_KEY=.*/$COLOR_KEY=\"${COLOR_MUTE}\"/"     "$STATE_FILE"
  sed -i "s/^$TIMESTAMP_KEY=.*/$TIMESTAMP_KEY=${now}/"        "$STATE_FILE"
  exit 0
fi

condition="${raw%%|*}"
temp_raw="${raw##*|}"

temp=$(echo "$temp_raw" | sed 's/[°C]//g' | sed 's/[^0-9-]//g')
[[ -z "$temp" ]] && temp=0

cond=$(echo "$condition" | tr '[:upper:]' '[:lower:]')

case "$cond" in
  *sun*|*clear*)       icon="$ICON_SUN"     ;;
  *partly*)            icon="$ICON_PARTLY"  ;;
  *cloud*|*overcast*)  icon="$ICON_CLOUD"   ;;
  *drizzle*)           icon="$ICON_DRIZZLE" ;;
  *rain*)              icon="$ICON_RAIN"    ;;
  *snow*)              icon="$ICON_SNOW"    ;;
  *storm*|*thunder*)   icon="$ICON_STORM"   ;;
  *fog*|*mist*|*haze*) icon="$ICON_FOG"     ;;
  *wind*)              icon="$ICON_WIND"    ;;
  *)                   icon="$ICON_UNKNOWN" ;;
esac

thresholds=(8           15           23        29             36)
colors=(    $COLOR_INFO $COLOR_WHITE $COLOR_OK $COLOR_WARNING $COLOR_DANGER)

color="${colors[-1]}"
for i in "${!thresholds[@]}"; do
  if (( temp < thresholds[i] )); then
    color="${colors[$i]}"
    break
  fi
done

value="${icon} ${temp_raw}"

source "${BAR_COMPONENTS_DIR}/scripts/state_loader"
state_update "$VALUE_KEY" "${value}"
state_update "$COLOR_KEY" "${color}"
state_update "$TIMESTAMP_KEY" "${now}"
