#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/state"

COM="${HOME}/.config/xmobar/com/page"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"

__number="page_number"
grep -q "^$__number=" "$STATE_FILE" || ( echo "$__number=1" >> "$STATE_FILE" && page_number=1 )

case "$1" in
  toggle) ${COM}/actions/toggle --value=${page_number} --STATE_FILE=${STATE_FILE} --KEY=${__number} ;;
  *) ;;
esac

[[ $page_number -eq 2 ]] && icon="󰔡" || icon="󰨙"

echo "${icon}${SEP}"
