#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/env"
source "${BAR_DIR}/scripts/render"

COM="$(resolve_component "brightness")"

xmobar_actions "$COM" \
  "4:up"              \
  "5:down"
