#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/env"
source "${BAR_DIR}/scripts/render"

COM="$(resolve_component "network")"

xmobar_actions "$COM" \
  "1:connect"         \
  "2:toggle"          \
  "3:traffic"
