#!/usr/bin/env bash

if [[ -z "$COLOR_OK" ]]; then
  source "${HOME}/.config/xmobar/scripts/vars"
fi

for arg in "$@"; do
  case $arg in
    --sep=*) custom_sep="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

xmobar_actions() {
  local script="$1"
  shift

  local text
  text="$("$script")" || return 0

  [[ -z ${text//[[:space:]]/} ]] && return 0
  sep="$([[ -z ${custom_sep//[[:space:]]/} ]] && printf '%s' "$SEP" || printf '%s' "$custom_sep")"

  local i
  for ((i=$#; i>0; i--)); do
    local action="${!i}"
    local button="${action%%:*}"
    local args="${action#*:}"
    text="<action=\`$script $args\` button=$button>$text</action>"
  done

  echo "${text} $sep "
}
