#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --value=*)    value="${arg#*=}" ;;
    --STATE_FILE=*) STATE_FILE="${arg#*=}" ;;
    --KEY=*) KEY="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

new_value=$(( value % 2 + 1 ))
sed -i "s/^$KEY=.*/$KEY=$new_value/" "$STATE_FILE"
