#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/env"
source "${BAR_COMPONENTS_DIR}/scripts/check_dependency"
check_dependency "scrot"
check_dependency "xrandr"
check_dependency "swappy"
check_dependency "xclip"

COM="${BAR_COMPONENTS_DIR}/com/screenshot"
[[ -n "$1" ]] && source "${STATE_FILE}"

DESTINATION="$HOME/screenshots"

source "${BAR_COMPONENTS_DIR}/scripts/state_loader"
source "${BAR_COMPONENTS_DIR}/scripts/tuples"
state_init "screenshot_edit" 0

case "$1" in
  take)   ${COM}/actions/take      \
    --DESTINATION=${DESTINATION} \
    --edit=${screenshot_edit} ;;
  toggle) ${COM}/actions/toggle  \
    --STATE_FILE=${STATE_FILE}   \
    --KEY=screenshot_edit        \
    --value=${screenshot_edit} ;;
  clear)  ${COM}/actions/clear \
    --DESTINATION=${DESTINATION} ;;
  *) ;;
esac

source "${BAR_COMPONENTS_DIR}/scripts/page/index" 2

color=$([[ $screenshot_edit -eq 0 ]] && echo "$COLOR_WHITE" || echo "$COLOR_WARNING")
emit_tuple 0 "$color" "󰹑"
emit_sep
