#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --type=*)        type="${arg#*=}" ;;
    --destination=*) destination="${arg#*=}" ;;
    --LOADING_KEY=*) LOADING_KEY="${arg#*=}" ;;
    --STATE_FILE=*)  STATE_FILE="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

extract_id() {
  case "$1" in
    *youtu.be/*) echo "${1#*youtu.be/}" | cut -d'?' -f1 | cut -d'&' -f1 | cut -d'/' -f1 ;;
    *v=*)        echo "${1#*v=}" | cut -d'&' -f1 ;;
    *shorts/*)   echo "${1#*shorts/}" | cut -d'?' -f1 | cut -d'/' -f1 ;;
    *) return 1 ;;
  esac
}

URL=$(rofi -dmenu -p "Youtube URL:")

VIDEO_ID=$(extract_id "$URL")

if [[ -z "$VIDEO_ID" ]]; then
  notify-send "yt-dlp" "Invalid YouTube URL"
  exit 1
fi

format=$([[ $type == 'mp4' ]] && echo "-f mp4" || echo "-t mp3")

sed -i "s/^$LOADING_KEY=.*/$LOADING_KEY=1/" "$STATE_FILE"

# Run download in background
(
  TITLE=$(yt-dlp \
    "$VIDEO_ID" \
    $format \
    -o "${destination}/%(title)s.%(ext)s" \
    --quiet \
    --no-progress \
    --no-warnings \
    --print after_move:title
  )
  FILENAME=$(printf "%s" "$TITLE" | rofi -dmenu -p "Filename:")

  if [[ -n "$FILENAME" && "$FILENAME" != "$TITLE" ]]; then
    mv "$destination/$TITLE.${type}" "$destination/$FILENAME.${type}"
  fi

  CLIP=$(rofi -dmenu -p "Clip (optional: 1:23-2:10)")
  if [[ "$CLIP" =~ ^[^-]+-[^-]+$ ]]; then
    INPUT="$destination/$FILENAME.${type}"
    OUTPUT="$destination/${FILENAME}_${START//:/-}_${END//:/-}.${type}"
    START="${CLIP%-*}"
    END="${CLIP#*-}"
    ffmpeg -ss "$START" -to "$END" -i "$INPUT" -c copy "$OUTPUT"

    rm "${INPUT}"
    mv "${OUTPUT}" "${INPUT}"
  fi

  sed -i "s/^$LOADING_KEY=.*/$LOADING_KEY=0/" "$STATE_FILE"
  notify-send "Finished: ${FILENAME}.${type}"
) &
