#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/page/index" 2

if ! command -v speedtest >/dev/null 2>&1; then
  echo "Warning: speedtest is not installed or not in PATH."
  exit 1
fi

COM="${HOME}/.config/xmobar/com/speedtest"
LOADING_FILE="${COM}/state/loading"
OUTPUT_FILE="${COM}/state/value"

if [ ! -f "$LOADING_FILE" ]; then
  echo 0 > "$LOADING_FILE"
fi

case "$1" in
  show) ${COM}/actions/show --OUTPUT_FILE=${OUTPUT_FILE} ;;
  test) ${COM}/actions/test --OUTPUT_FILE=${OUTPUT_FILE} --LOADING_FILE=${LOADING_FILE} ;;
esac

is_loading=$(cat "$LOADING_FILE")

if (( is_loading == 0 )); then
  echo "󰾆${SEP}"
fi

if (( is_loading == 1 )); then
  echo "<fc=${COLOR_INFO}>  Testing... 󰓅 </fc>${SEP}"
fi

# Check if we need to update cache
if [[ -f "$OUTPUT_FILE" ]]; then
  # Read timestamp from the last line (4th field)
  last_ts=$(awk -F'|' '{print $4}' "$OUTPUT_FILE")
else
  last_ts=0
fi

now=$(date +%s)
if (( now - last_ts >= 3600 )); then
  $(${COM}/scripts/runner --OUTPUT_FILE=${OUTPUT_FILE} &)
fi
