#!/usr/bin/env bash


source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/state"
source "${HOME}/.config/xmobar/scripts/page/index" 2

if ! command -v speedtest >/dev/null 2>&1; then
  echo "Warning: speedtest is not installed or not in PATH."
  exit 1
fi

COM="${HOME}/.config/xmobar/com/speedtest"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"

__loading="speedtest_loading"
__isp="speedtest_isp"
__up="speedtest_up"
__down="speedtest_down"
__timestamp="speedtest_timestamp"

now=$(date +%s)
grep -q "^$__isp=" "$STATE_FILE"       || ( echo "$__isp=UNKNOWN" >> "$STATE_FILE" && speedtest_isp="UNKNOWN" )
grep -q "^$__up=" "$STATE_FILE"        || ( echo "$__up=0" >> "$STATE_FILE" && speedtest_up=0 )
grep -q "^$__down=" "$STATE_FILE"      || ( echo "$__down=0" >> "$STATE_FILE" && speedtest_down=0 )
grep -q "^$__timestamp=" "$STATE_FILE" || ( echo "$__timestamp=$(($now - 3601 ))" >> "$STATE_FILE" && speedtest_timestamp=$(($now - 3601 ))  )
grep -q "^$__loading=" "$STATE_FILE"   || ( echo "$__loading=0" >> "$STATE_FILE" && speedtest_loading=0 )

case "$1" in
  show) ${COM}/actions/show --isp="${speedtest_isp}" --down=${speedtest_down} --up=${speedtest_up} --timestamp=${speedtest_timestamp} ;;
  test) ${COM}/actions/test --STATE_FILE=${STATE_FILE} --ISP_KEY=${__isp} --UP_KEY=${__up} --DOWN_KEY=${__down} --TIMESTAMP_KEY=${__timestamp} --LOADING_KEY=${__loading};;
  *) ;;
esac

if (( speedtest_loading == 0 )); then
  echo "󰾆${SEP}"
fi

if (( speedtest_loading == 1 )); then
  echo "<fc=${COLOR_INFO}>  Testing... 󰓅 </fc>${SEP}"
fi

if (( now - speedtest_timestamp >= 3600 )); then
 $(${COM}/scripts/runner --STATE_FILE=${STATE_FILE} --ISP_KEY=${__isp} --UP_KEY=${__up} --DOWN_KEY=${__down} --TIMESTAMP_KEY=${__timestamp} &)
fi
