#!/usr/bin/env bash

COM="${HOME}/.config/xmobar/com/battery"
[[ -n "$1" ]] && STATE_FILE="${HOME}/.config/xmobar/scripts/state" && source "${STATE_FILE}"
source "${HOME}/.config/xmobar/scripts/page/index" 1

source "${HOME}/.config/xmobar/scripts/cache"

now=$(date +%s)
CACHE_TTL=80 # seconds

source "${HOME}/.config/xmobar/scripts/state_loader"
state_init "battery_level_icon" 0
state_init "battery_show_time" 0
state_init "battery_info" ""
state_init "battery_timestamp" $((now - 81))

if ! command -v acpi >/dev/null 2>&1; then
  echo "Warning: acpi is not installed or not in PATH."
  exit 1
fi

# If acpi output does NOT contain "Battery", then exit
echo "$battery_info" | grep -q "Battery" || exit 0

# Refresh cache if older than CACHE_TTL
if (( now - battery_timestamp >= CACHE_TTL )); then
  battery_info="$(acpi -b 2>/dev/null)"
  state_update "battery_info" "\"$battery_info\""
  state_update "battery_timestamp" "$now"
fi

state=$(echo "$battery_info" | awk -F'[,: ]+' '{print $3}')
level=$(echo "$battery_info" | awk -F'[,% ]+' '{print $4}')
time=$(echo "$battery_info"  | awk '{for(i=1;i<=NF;i++){if($i~/[0-9][0-9]:[0-9][0-9]:[0-9][0-9]/) print $i}}')

thresholds=(10 33 66 85 95)
icons=("󰢟" "󱊤" "󱊥" "󱊦" "󰂅")

case "$1" in
  show_time) ${COM}/actions/show_time \
    --value=${battery_show_time}      \
    --STATE_FILE=${STATE_FILE}        \
    --KEY=battery_show_time ;;
  *) ;;
esac

if [[ "$state" == "Full" ]]; then
  echo "<fc=${COLOR_WHITE}></fc>"
  exit 0
fi

if [[ "$state" == "Not" ]]; then
  echo "<fc=${COLOR_WHITE}>!</fc>"
  exit 0;
fi

if [[ "$state" == "Charging" ]]; then

  usable_icons=()
  for i in "${!thresholds[@]}"; do
    if [[ "$level" -le "${thresholds[$i]}" ]]; then
        usable_icons+=("${icons[$i]}")
    fi
  done

  # Safety fallback
  [[ ${#usable_icons[@]} -eq 0 ]] && usable_icons=("${icons[$((${#icons[@]} - 1))]}")

  idx=$(( (battery_level_icon + 1) % ${#usable_icons[@]} ))
  state_update "battery_level_icon" "$idx"

  timercolor="${COLOR_OK}"
  icon="${usable_icons[$idx]} <fc=$timercolor>${level}󰏰</fc>"
  [[ $battery_show_time == 1 ]] && icon="$icon  <fc=$timercolor> $time </fc>"
  echo "${icon}"
  exit 0
fi

# Otherwise output normal code
if [[ "$state" == "Discharging" ]]; then
  thresholds=(10 33 66)
  icons=("󰂎" "󱊡" "󱊢" "󱊣")
  timercolors=($COLOR_CRITIC $COLOR_DANGER $COLOR_WARNING $COLOR_OK)

  icon="${icons[-1]}  ${level}󰏰"
  timercolor=${timercolors[-1]}
  for i in "${!thresholds[@]}"; do
    if (( level < thresholds[i] )); then
      icon="${icons[i]} ${level}󰏰"
      timercolor=${timercolors[i]}
      break
    fi
  done
else
  icon="󰂃"
fi

output=$([[ $level -le ${thresholds[1]} ]] && echo "<fc=$timercolor>$icon</fc>" || echo ${icon} )
output=$([[ $battery_show_time -eq 1 ]] && echo $output || echo "$output <fc=$timercolor> $time </fc>" )
echo "${output}"
