#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
source "${BAR_DIR}/scripts/render"

COM="$(resolve_component "speedtest")"

xmobar_actions "$COM" \
  "1:show"            \
  "3:run"
