#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/page/index" 1

if ! command -v brightnessctl >/dev/null 2>&1; then
  echo "Warning: brightnessctl is not installed or not in PATH."
  exit 1
fi

if ! command -v brightnessctl >/dev/null 2>&1 || \
   ! brightnessctl -l | grep -q "backlight"; then
    exit 0
fi

if ! command -v xob >/dev/null 2>&1; then
  echo "Warning: xob is not installed or not in PATH."
  exit 1
fi

COM="${HOME}/.config/xmobar/com/brightness"

# Optional: control mode
STEP=${2:-3}

BL_DIR="/sys/class/backlight/intel_backlight"  # your backlight folder
cur=$(<"$BL_DIR/brightness")
max=$(<"$BL_DIR/max_brightness")
percent=$((100 * cur / max))

case "$1" in
  up)   ${COM}/actions/brightness_up   --step=${STEP} --percent=${percent} ;;
  down) ${COM}/actions/brightness_down --step=${STEP} --percent=${percent} ;;
  *) ;;
esac


thresholds=(13 30 40 50 60 70 80 90)
icons=(󰪞 󰪟 󰪠 󰪡 󰪢 󰪣 󰪤 󰪥 )

icon=${icons[-1]}
for i in "${!thresholds[@]}"; do
  if (( percent < thresholds[i] )); then
    icon="${icons[i]}"
    break
  fi
done

echo "$icon $percent󰏰"
