#!/usr/bin/env bash

# Vars/state already exported from scripts/bar
source "${HOME}/.config/xmobar/scripts/page/index" 2

case "$1" in
  change) "${HOME}/.config/xmobar/com/rofi_theme/actions/change_theme" ;;
  *) ;;
esac

echo "󰔎"
