#!/usr/bin/env bash

# Vars/state already exported from scripts/bar
source "${HOME}/.config/xmobar/scripts/state_loader"

COM="${HOME}/.config/xmobar/com/calendar"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"

# Initialize state if needed
state_init "calendar_toggle" 0

# If action is called, re-source state to get current values
if [[ -n "$1" ]]; then
  source "${STATE_FILE}"
fi

if ! command -v yad >/dev/null 2>&1; then
  echo "Warning: yad is not installed or not in PATH."
fi

case "$1" in
  toggle) ${COM}/actions/toggle \
    --value=${calendar_toggle}  \
    --STATE_FILE=${STATE_FILE}  \
    --KEY=calendar_toggle
    # Re-source state after action to get updated value
    source "${STATE_FILE}" ;;
  show_calendar) ${COM}/actions/show_calendar;;
  *) ;;
esac

declare -A ICONS=(
  [00]=""
  [01]=""
  [02]=""
  [03]=""
  [04]=""
  [05]=""
  [06]=""
  [07]=""
  [08]=""
  [09]=""
  [10]=""
  [11]=""
  [12]="󱑊"
  [13]="󱐿"
  [14]="󱑀"
  [15]="󱑁"
  [16]="󱑂"
  [17]="󱑃"
  [18]="󱑄"
  [19]="󱑅"
  [20]="󱑆"
  [21]="󱑇"
  [22]="󱑈"
  [23]="󱑉"
)

format=$([[ calendar_toggle -eq 1 ]] && echo "%d-%m-%Y" || echo "%H:%M:%S" )
icon=$([[   calendar_toggle -eq 1 ]] && echo " "                || echo "<fn=1>${ICONS[$(date +%H)]}</fn>" )
color=$([[  calendar_toggle -eq 1 ]] && echo ${COLOR_WARNING} || echo ${COLOR_OK} )

echo "<fc=${color}>${icon} $(date +"$format")</fc>"
