#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
COM="${BAR_COMPONENTS_DIR}/com/space"
[[ -n "$1" ]] && source "${STATE_FILE}"
page_guard 1

state_init "space_toggle" 0

case "$1" in
  show)   ${COM}/actions/show ;;
  toggle) ${COM}/actions/toggle \
    --value=${space_toggle}     \
    --STATE_FILE=${STATE_FILE}  \
    --KEY=space_toggle ;;
  *) ;;
esac

formats=("avail" "used")
colors=("$COLOR_WHITE" "$COLOR_WARNING")

root="$(df -h --output=${formats[$space_toggle]} /     | tail -1 | tr -d ' ')"
home="$(df -h --output=${formats[$space_toggle]} /home | tail -1 | tr -d ' ')"

emit_tuple 0 "${colors[$space_toggle]}" "${root} / ${home}"
emit_sep
