#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"

OPTIONS=(
  "⏼  Shutdown"
  "󰑓  Restart"
  "󰗽  Logout"
)

open() {

  CHOICE=$(printf "%s\n" "${OPTIONS[@]}" | rofi -dmenu -i -p "Power Options")
  ACTION=$(echo "$CHOICE" | sed 's/^[^ ]*  //')

  case "$ACTION" in
    "Shutdown")
      doas $(which poweroff)
      ;;
    "Restart")
      doas $(which reboot)
      ;;
    "Logout")
      pkill X
      ;;
  esac
}

case "$1" in
  open) open ;;
  *) ;;
esac

icon="󰐥"
echo "${icon}${SEP}"
