#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --path=*)       path="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done


nsxiv -otb $path
