#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

$TERM --class float-large -e ${HOME}/.config/_scripts/startup/automount/automount-tui.sh >/dev/null
