#!/usr/bin/env bash

# Vars/state already exported from scripts/bar
source "${HOME}/.config/xmobar/scripts/state_loader"
source "${HOME}/.config/xmobar/scripts/page/index" 1

COM="${HOME}/.config/xmobar/com/vpn"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"
VPN_CONF="/opt/vpn/popcash.conf"
VPN_PID_FILE="/opt/vpn/openvpn.pid"

# Initialize state keys if needed
state_init "vpn_toggle" 0
state_init "vpn_loading" 0
state_init "vpn_spinner" 0


# If action is called, re-source state to get current values
if [[ -n "$1" ]]; then
  source "${STATE_FILE}"
fi

case "$1" in
  up) ${COM}/actions/up        \
    --STATE_FILE=${STATE_FILE} \
    --TOGGLE_KEY=vpn_toggle    \
    --LOADING_KEY=vpn_loading  \
    --CONF_FILE=${VPN_CONF}    \
    --PID_FILE=${VPN_PID_FILE}
    # Re-source state after action to get updated value
    source "${STATE_FILE}" ;;

  down) ${COM}/actions/down    \
    --STATE_FILE=${STATE_FILE} \
    --TOGGLE_KEY=vpn_toggle    \
    --LOADING_KEY=vpn_loading  \
    --PID_FILE=${VPN_PID_FILE}
    # Re-source state after action to get updated value
    source "${STATE_FILE}" ;;
  *) ;;
esac

if (( vpn_loading == 1 )); then
  spinner_icons=(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
  idx=$(( ( vpn_spinner + 1 ) % ${#spinner_icons[@]} ))
  state_update "vpn_spinner" "$idx"

  echo "<fc=${COLOR_INFO}>${spinner_icons[$idx]}  Connecting  󰇠</fc>"
  exit 0
fi

colors=(${COLOR_MUTE} ${COLOR_OK})
icons=(󰯄  󰦝)

echo "<fc=${colors[vpn_toggle]}>${icons[vpn_toggle]}</fc>"
