#!/usr/bin/env bash

COM="${HOME}/.config/xmobar/com/space"
[[ -n "$1" ]] && STATE_FILE="${HOME}/.config/xmobar/scripts/state" && source "${STATE_FILE}"
source "${HOME}/.config/xmobar/scripts/page/index" 1

source "${HOME}/.config/xmobar/scripts/state_loader"
state_init "space_toggle" 0

case "$1" in
  toggle) ${COM}/actions/toggle \
    --value=${space_toggle}     \
    --STATE_FILE=${STATE_FILE}  \
    --KEY=space_toggle ;;
  *) ;;
esac

formats=("avail" "used")
colors=(${COLOR_WHITE} ${COLOR_WARNING})

root="$(df -h --output=${formats[$space_toggle]} /     | tail -1)"
home="$(df -h --output=${formats[$space_toggle]} /home | tail -1)"

echo "<fc=${colors[$space_toggle]}> ${root} /${home}</fc>"
