#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/state"
source "${HOME}/.config/xmobar/scripts/page/index" 1

COM="${HOME}/.config/xmobar/com/vpn"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"
VPN_CONF="/opt/vpn/popcash.conf"
VPN_PID_FILE="/opt/vpn/openvpn.pid"

__toggle="vpn_toggle"
__loading="vpn_loading"
__spinner="vpn_spinner"
grep -q "^$__toggle"  "$STATE_FILE" || ( echo "$__toggle=0"  >> "$STATE_FILE" && vpn_toggle=0)
grep -q "^$__loading" "$STATE_FILE" || ( echo "$__loading=0" >> "$STATE_FILE" && vpn_loading=0)
grep -q "^$__spinner" "$STATE_FILE" || ( echo "$__spinner=0" >> "$STATE_FILE" && vpn_spinner=0)

case "$1" in
  up)   ${COM}/actions/up   --STATE_FILE=${STATE_FILE} --TOGGLE_KEY=${__toggle} --LOADING_KEY=${__loading}  --CONF_FILE=${VPN_CONF} --PID_FILE=${VPN_PID_FILE} ;;
  down) ${COM}/actions/down --STATE_FILE=${STATE_FILE} --TOGGLE_KEY=${__toggle} --LOADING_KEY=${__loading} --PID_FILE=${VPN_PID_FILE} ;;
  *) ;;
esac

if (( vpn_loading == 1 )); then
  spinner_icons=(      )
  idx=$(( ( vpn_spinner + 1 ) % ${#spinner_icons[@]} ))

  echo "$idx" > "$SPINNER_FILE"
  sed -i "s/^$__spinner=.*/$__spinner=$idx/" "$STATE_FILE"

  echo "<fc=${COLOR_INFO}>${spinner_icons[$idx]}  Connecting  󰇠</fc>${SEP}"
  exit 0
fi

colors=(${COLOR_MUTE} ${COLOR_OK})
icons=(󰯄  󰦝)

echo "<fc=${colors[vpn_toggle]}>${icons[vpn_toggle]}</fc>${SEP}"
