#!/usr/bin/env bash

COM="${HOME}/.config/xmobar/com/calendar"
[[ -n "$1" ]] && STATE_FILE="${HOME}/.config/xmobar/scripts/state" && source "${STATE_FILE}"

source "${HOME}/.config/xmobar/scripts/state_loader"
state_init "calendar_toggle" 0

if ! command -v yad >/dev/null 2>&1; then
  echo "Warning: yad is not installed or not in PATH."
fi

case "$1" in
  toggle) ${COM}/actions/toggle \
    --value=${calendar_toggle}  \
    --STATE_FILE=${STATE_FILE}  \
    --KEY=calendar_toggle ;;
  show_calendar) ${COM}/actions/show_calendar;;
  *) ;;
esac

declare -A ICONS=(
  [00]=""
  [01]=""
  [02]=""
  [03]=""
  [04]=""
  [05]=""
  [06]=""
  [07]=""
  [08]=""
  [09]=""
  [10]=""
  [11]=""
  [12]="󱑊"
  [13]="󱐿"
  [14]="󱑀"
  [15]="󱑁"
  [16]="󱑂"
  [17]="󱑃"
  [18]="󱑄"
  [19]="󱑅"
  [20]="󱑆"
  [21]="󱑇"
  [22]="󱑈"
  [23]="󱑉"
)

format=$([[ calendar_toggle -eq 1 ]] && echo "%d-%m-%Y" || echo "%H:%M:%S" )
icon=$([[   calendar_toggle -eq 1 ]] && echo " "                || echo "<fn=1>${ICONS[$(date +%H)]}</fn>" )
color=$([[  calendar_toggle -eq 1 ]] && echo ${COLOR_WARNING} || echo ${COLOR_OK} )

echo "<fc=${color}>${icon} $(date +"$format")</fc>"
