#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
source "${BAR_DIR}/scripts/render"

COM="$(resolve_component "calendar")"

xmobar_actions "$COM" \
  "1:toggle"          \
  "3:show_calendar"
