#!/usr/bin/env bash
# xbps-install libspa-bluetooth -- bluetooth support for audio

source "${HOME}/.config/barlib/scripts/init"
COM="${BAR_COMPONENTS_DIR}/com/volume_output"
[[ -n "$1" ]] && source "${STATE_FILE}"
page_guard 1

ICON_SPEAKER="󰓃"
ICON_JACK_HEADPHONES="󱡬 󰋋"
ICON_USB_HEADPHONES="  󰋋"
ICON_WIRELESS_HEADPHONES=" 󰋋"
ICON_DEAD="󰓄"
default_sink="@DEFAULT_AUDIO_SINK@"

get_sink_icon() {
  local INFO
  INFO="$(wpctl inspect "${default_sink}")"
  case "$INFO" in
    *'device.api = "bluez5"'*)               echo "${ICON_WIRELESS_HEADPHONES}" ;;
    *'device.bus = "usb"'*)                  echo "${ICON_USB_HEADPHONES}" ;;
    *'port.name = "analog-output-headphones"'*|\
    *'port.name = "analog-output-headset"'*) echo "${ICON_JACK_HEADPHONES}" ;;
    '') echo "${ICON_DEAD}" ;;
    *)  echo "${ICON_SPEAKER}" ;;
  esac
}

case "$1" in
  info)   ${COM}/actions/info ;;
  toggle) ${COM}/actions/cycle_output ;;
  *) ;;
esac

icon=$(get_sink_icon)
color=$([[ $icon == "${ICON_DEAD}" ]] && echo "${COLOR_DANGER}" || echo "$COLOR_INFO")

emit_tuple 0 "$color" "$icon"
emit_sep
