#!/usr/bin/env bash
# xbps-install libspa-bluetooth -- bluetooth support for audio

source "${HOME}/.config/barlib/scripts/env"
COM="${BAR_COMPONENTS_DIR}/com/volume_output"
[[ -n "$1" ]] && source "${STATE_FILE}"
source "${BAR_COMPONENTS_DIR}/scripts/page/index" 1
source "${BAR_COMPONENTS_DIR}/scripts/tuples"

ICON_SPEAKER="󰓃"
ICON_JACK_HEADPHONES="󱡬 󰋋"
ICON_USB_HEADPHONES="  󰋋"
ICON_WIRELESS_HEADPHONES=" 󰋋"
default_sink="@DEFAULT_AUDIO_SINK@"

get_sink_icon() {
  local INFO
  INFO="$(wpctl inspect "${default_sink}")"
  case "$INFO" in
    *'device.api = "bluez5"'*)               echo "${ICON_WIRELESS_HEADPHONES}" ;;
    *'device.bus = "usb"'*)                  echo "${ICON_USB_HEADPHONES}" ;;
    *'port.name = "analog-output-headphones"'*|\
    *'port.name = "analog-output-headset"'*) echo "${ICON_JACK_HEADPHONES}" ;;
    '') echo "-1" ;;
    *)  echo "${ICON_SPEAKER}" ;;
  esac
}

case "$1" in
  info)   ${COM}/actions/info ;;
  toggle) ${COM}/actions/cycle_output ;;
  *) ;;
esac

icon=$(get_sink_icon)
[[ "$icon" == "-1" ]] && exit 0

emit_tuple 0 "$COLOR_INFO" "$icon"
emit_sep
