#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --TRAFFIC_FILE=*) TRAFFIC_FILE="${arg#*=}" ;;
    --show_traffic=*) show_traffic="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done


toggle=$((1 - show_traffic))
echo "$toggle" > "$TRAFFIC_FILE"

exit 0;
