#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/check_dependency"
check_dependency "xset" --exit

COM="${HOME}/.config/xmobar/com/capslock"
[[ -n "$1" ]] && STATE_FILE="${HOME}/.config/xmobar/scripts/state" && source "${STATE_FILE}"

source "${HOME}/.config/xmobar/scripts/vars"

if xset q | grep -q "Caps Lock: *on"; then
  echo "<fc=${COLOR_WARNING}><fn=1>󰪛</fn></fc>"
fi
