#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
COM="${BAR_COMPONENTS_DIR}/com/power"


[[ -n "$1" ]] && source "${STATE_FILE}"

case "$1" in
  open) "${COM}/actions/show" ;;
  *) ;;
esac

emit_tuple 0 "$COLOR_WHITE" "󰐥"
emit_sep
