#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --STATE_FILE=*) STATE_FILE="${arg#*=}" ;;
    --TOGGLE_KEY=*) TOGGLE_KEY="${arg#*=}" ;;
    --LOADING_KEY=*) LOADING_KEY="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

doas /usr/sbin/killall openvpn>/dev/null 2>&1
sed -i "s/^$TOGGLE_KEY=.*/$TOGGLE_KEY=0/" "$STATE_FILE"
sed -i "s/^$LOADING_KEY=.*/$LOADING_KEY=0/" "$STATE_FILE"
