#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --LABEL_FILE=*) LABEL_FILE="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

echo -1 > "$LABEL_FILE"
