#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
COM="${BAR_COMPONENTS_DIR}/com/rofi_theme"
[[ -n "$1" ]] && source "${STATE_FILE}"
page_guard 2


case "$1" in
  change) "${COM}/actions/change_theme" ;;
  *) ;;
esac

emit_tuple 0 "$COLOR_WHITE" "󰔎"
emit_sep
