#!/usr/bin/env bash
# xbps-install libspa-bluetooth -- bluetooth support for audio

# Vars/state already exported from scripts/bar
source "${HOME}/.config/xmobar/scripts/page/index" 1

COM="${HOME}/.config/xmobar/com/volume_output"

ICON_SPEAKER="󰓃"
ICON_JACK_HEADPHONES="󱡬 󰋋"
ICON_USB_HEADPHONES="  󰋋"
ICON_WIRELESS_HEADPHONES=" 󰋋"

# ------------------------------

default_sink="@DEFAULT_AUDIO_SINK@"

get_volume() {
  wpctl get-volume "${default_sink}" | awk '{printf "%.0f\n", $2 * 100}'
}

get_sink_icon() {
  INFO="$(wpctl inspect ${default_sink})"


  case "$INFO" in
    *'device.api = "bluez5"'*) echo "${ICON_WIRELESS_HEADPHONES}" ;;
    *'device.bus = "usb"'*) echo "${ICON_USB_HEADPHONES}" ;;

    # Wired headset (jack)
    *'port.name = "analog-output-headphones"'*|\
    *'port.name = "analog-output-headset"'*)
      echo "$ICON_JACK_HEADPHONES" ;;

    '') echo "-1" ;;
    * ) echo "${ICON_SPEAKER}" ;;
  esac
}

case "$1" in
  info) ${COM}/actions/info ;;
  toggle) ${COM}/actions/cycle_output ;;
  *) ;;
esac


icon=$(get_sink_icon)
[[ $icon == '-1' ]] && exit 0

echo "<fc=${COLOR_INFO}>$icon</fc>"
