#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/state"

COM="${HOME}/.config/xmobar/com/calendar"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"
__toggle="calendar_toggle"

grep -q "^$__toggle=" "$STATE_FILE" || echo "$__toggle=0" >> "$STATE_FILE"

if ! command -v yad >/dev/null 2>&1; then
  echo "Warning: yad is not installed or not in PATH."
fi

case "$1" in
  toggle) ${COM}/actions/toggle --calendar_toggle=${calendar_toggle} --STATE_FILE=${STATE_FILE} --KEY=${__toggle} ;;
  show_calendar) ${COM}/actions/show_calendar;;
  *) ;;
esac

format="%H:%M:%S"
[[ calendar_toggle -eq 1 ]] && format="%d-%m-%Y"

declare -A ICONS=(
    [0]=""
    [1]=""
    [2]=""
    [3]=""
    [4]=""
    [5]=""
    [6]=""
    [7]=""
    [8]=""
    [9]=""
    [10]=""
    [11]=""
    [12]="󱑊"
    [13]="󱐿"
    [14]="󱑀"
    [15]="󱑁"
    [16]="󱑂"
    [17]="󱑃"
    [18]="󱑄"
    [19]="󱑅"
    [20]="󱑆"
    [21]="󱑇"
    [22]="󱑈"
    [23]="󱑉"
)

[[ calendar_toggle -eq 1 ]] && icon=" " || icon="${ICONS[$(date +%H)]}"
[[ calendar_toggle -eq 1 ]] && color="${COLOR_WARNING}" || color="${COLOR_OK}"

echo "<fc=${color}>${icon}  $(date +"$format")</fc>${SEP}"
