#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/env"
COM="${BAR_COMPONENTS_DIR}/com/weather"
[[ -n "$1" ]] && source "${STATE_FILE}"
source "${BAR_COMPONENTS_DIR}/scripts/page/index" 2

now=$(date +%s)

source "${BAR_COMPONENTS_DIR}/scripts/state_loader"
source "${BAR_COMPONENTS_DIR}/scripts/tuples"
state_init "weather_value" ""
state_init "weather_timestamp" $((now - 3601))
state_init "weather_loading_live" 0
state_init "weather_spinner" 0

case "$1" in
  run) ${COM}/actions/run             \
    --STATE_FILE=${STATE_FILE}        \
    --TIMESTAMP_KEY=weather_timestamp \
    --VALUE_KEY=weather_value         \
    --LOADING_KEY=weather_loading_live ;;
  *) ;;
esac

if (( weather_loading_live == 1 )); then
  spinner_icons=(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
  idx=$(( ( weather_spinner + 1 ) % ${#spinner_icons[@]} ))
  state_update "weather_spinner" "$idx"
  emit_tuple 0 "$COLOR_INFO" "${spinner_icons[$idx]} Update...󱣶 "
  emit_sep
  exit 0
fi

emit_tuple 0 "$COLOR_WHITE" "$weather_value"
emit_sep
