#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --sink=*)     sink="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

wpctl set-mute "${sink}" toggle
echo 0! > "${HOME}/.config/xob/volume/value"
