#!/usr/bin/env bash

# Vars/state already exported from scripts/bar
source "${HOME}/.config/xmobar/scripts/state_loader"

COM="${HOME}/.config/xmobar/com/page"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"

# Initialize state if needed
state_init "page_number" 1


# If action is called, re-source state to get current values
if [[ -n "$1" ]]; then
  source "${STATE_FILE}"
fi

case "$1" in
  toggle) ${COM}/actions/toggle \
    --value=${page_number}      \
    --STATE_FILE=${STATE_FILE}  \
    --KEY=page_number
    # Re-source state after action to get updated value
    source "${STATE_FILE}" ;;
  *) ;;
esac

icon=$([[ $page_number -eq 2 ]] && echo "󰔡" || echo "󰨙")
echo "${icon}"
