#!/usr/bin/env bash

# Vars/state already exported from scripts/bar
source "${HOME}/.config/xmobar/scripts/state_loader"

DESTINATION="$HOME/screenshots"

COM="${HOME}/.config/xmobar/com/screenshot"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"

# Initialize state if needed
state_init "screenshot_edit" 0


# If action is called, re-source state to get current values
if [[ -n "$1" ]]; then
  source "${STATE_FILE}"
fi

case "$1" in
  take) ${COM}/actions/take      \
    --DESTINATION=${DESTINATION} \
    --edit=${screenshot_edit} ;;

  toggle) ${COM}/actions/toggle  \
    --STATE_FILE=${STATE_FILE}   \
    --KEY=screenshot_edit        \
    --value=${screenshot_edit}
    # Re-source state after action to get updated value
    source "${STATE_FILE}" ;;

  clear) ${COM}/actions/clear \
    --DESTINATION=${DESTINATION} ;;
  *) ;;
esac

source "${HOME}/.config/xmobar/scripts/page/index" 2

if ! command -v scrot >/dev/null 2>&1; then
  echo "Warning: scrot is not installed or not in PATH."
  exit 1
fi

if ! command -v xrandr >/dev/null 2>&1; then
  echo "Warning: xrandr is not installed or not in PATH."
  exit 1
fi

if ! command -v swappy >/dev/null 2>&1; then
  echo "Warning: swappy is not installed or not in PATH."
  exit 1
fi

if ! command -v xclip >/dev/null 2>&1; then
  echo "Warning: xclip is not installed or not in PATH."
  exit 1
fi

color=$([[ $screenshot_edit -eq 0 ]] && echo "${COLOR_WHITE}" || echo "${COLOR_WARNING}")
echo "<fc=${color}>󰹑</fc>"
