#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/page/index" 2

COM="${HOME}/.config/xmobar/com/automount"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"
CONFIG_FILE="${HOME}/.config/_scripts/startup/automount/automount.conf"

# If action is called, re-source state to get current values
if [[ -n "$1" ]]; then
  source "${STATE_FILE}"
fi

case "$1" in
  toggle) ${COM}/actions/toggle ;;
esac

count=$(grep -c "^NEW=yes$" "$CONFIG_FILE" 2>/dev/null)

color=$(  [[ count -gt 0 ]] && echo ${COLOR_WARNING} || echo ${COLOR_WHITE} )
counter=$([[ count -gt 0 ]] && echo " ${count}" || echo "" )

echo "<fc=${color}>󱛟$counter</fc>"
