#!/usr/bin/env bash

COM="${HOME}/.config/xmobar/com/bluetooth"
[[ -n "$1" ]] && STATE_FILE="${HOME}/.config/xmobar/scripts/state" && source "${STATE_FILE}"
source "${HOME}/.config/xmobar/scripts/page/index" 1

source "${HOME}/.config/xmobar/scripts/cache"

source "${HOME}/.config/xmobar/scripts/state_loader"
state_init "bluetooth_index_device" -1

if ! command -v bluetoothctl >/dev/null 2>&1; then
  echo "Warning: bluetoothctl is not installed or not in PATH."
  exit 1
fi

if ! command -v upower >/dev/null 2>&1; then
  echo "Warning: upower is not installed or not in PATH."
  exit 1
fi

if ! command -v bluetuith >/dev/null 2>&1; then
  echo "Warning: bluetuith is not installed or not in PATH."
fi


STATE_FILE_LOADER="${HOME}/.config/xmobar/scripts/state_loader"

state=$(bluetoothctl show | awk '/Powered/ {print ($2=="yes"?1:0)}')

outputColor=${COLOR_WHITE}
disabledColor=${COLOR_MUTE}
thresholds=(10 33 66)
timercolors=(${COLOR_CRITIC} ${COLOR_DANGER}  ${COLOR_WARNING} ${COLOR_OK})

mapfile -t connectedDevices < <(
  bluetoothctl devices Connected | sed 's/^Device [A-F0-9:]* //'
)

if [ ${#connectedDevices[@]} -eq 0 ]; then
  state_update "bluetooth_index_device" -1
fi

case "$1" in
  open) ${COM}/actions/open ;;

  toggle) ${COM}/actions/toggle \
    --state=${state} ;;

  reset) ${COM}/actions/reset                \
    --STATE_FILE=${STATE_FILE}               \
    --STATE_FILE_LOADER=${STATE_FILE_LOADER} \
    --KEY=bluetooth_index_device ;;

  cycle_up) ${COM}/actions/cycle_up          \
    --STATE_FILE=${STATE_FILE}               \
    --STATE_FILE_LOADER=${STATE_FILE_LOADER} \
    --KEY=bluetooth_index_device             \
    --currentIndex=${bluetooth_index_device} \
    --count=${#connectedDevices[@]} ;;

  cycle_down) ${COM}/actions/cycle_up        \
    --STATE_FILE=${STATE_FILE}               \
    --STATE_FILE_LOADER=${STATE_FILE_LOADER} \
    --KEY=bluetooth_index_device             \
    --currentIndex=${bluetooth_index_device} \
    --count=${#connectedDevices[@]} ;;
  *) ;;
esac

if [[ $bluetooth_index_device -eq -1 ]]; then
  connectedCount=${#connectedDevices[@]}
  label=" ${connectedCount} devices"
  if [ "$connectedCount" -eq 1 ]; then
    label=" ${connectedCount} device"
  elif [ "$connectedCount" -eq 0 ]; then
    label=""
  fi
else
  percentage=$(upower --dump | awk -v name="${connectedDevices[$bluetooth_index_device]}" '
      /^ *model:/ {
          # rebuild the model name after the colon
          $1=""; sub(/^ +/, "", $0)
          if ($0 == name) found=1
      }
      found && /percentage:/ {
          gsub("%","",$2)
          print $2
          exit
      }
  ')

  if [[ -z "$percentage" ]]; then
    percentage=100
  fi

  outputColor=${timercolors[${#timercolors[@]}-1]}
  for i in "${!thresholds[@]}"; do
    if (( percentage < thresholds[i] )); then
      outputColor=${timercolors[i]}
      break
    fi
  done
  label=" <fc=${outputColor}>$((bluetooth_index_device + 1))/${#connectedDevices[@]} ${connectedDevices[$bluetooth_index_device]} $percentage󰏰</fc>"
fi

icons=("󰂲" "󰂰")
colors=(${disabledColor} ${outputColor})

echo "<fc=${colors[$state]}>${icons[$state]}${label}</fc>"
