#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
source "${BAR_DIR}/scripts/render"

COM="$(resolve_component "bluetooth")"

xmobar_actions "$COM" \
  "1:open"            \
  "2:toggle"          \
  "3:reset"           \
  "4:cycle_up"        \
  "5:cycle_down"
