name : xmonad-config
version : 0.1.0
dependencies :
  - base >= 4.14 && < 5
  - xmonad == 0.18.0
  - xmonad-contrib == 0.18.1
  - containers
  - X11

executables :
  xmonad :
    main:  xmonad.hs
    ghc-options :
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
