#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/env"
source "${BAR_COMPONENTS_DIR}/scripts/check_dependency"
check_dependency "brightnessctl"
check_dependency "xob"

COM="${BAR_COMPONENTS_DIR}/com/brightness"
[[ -n "$1" ]] && source "${STATE_FILE}"
source "${BAR_COMPONENTS_DIR}/scripts/page/index" 1
source "${BAR_COMPONENTS_DIR}/scripts/tuples"

if ! brightnessctl -l | grep -q "backlight"; then
  exit 0
fi

STEP=${2:-3}
BL_DIR="/sys/class/backlight/intel_backlight"
cur=$(<"$BL_DIR/brightness")
max=$(<"$BL_DIR/max_brightness")
percent=$((100 * cur / max))

case "$1" in
  up)   ${COM}/actions/brightness_up   --step=${STEP} --percent=${percent} ;;
  down) ${COM}/actions/brightness_down --step=${STEP} --percent=${percent} ;;
  *) ;;
esac

thresholds=(13 30 40 50 60 70 80 90)
icons=(󰪞 󰪟 󰪠 󰪡 󰪢 󰪣 󰪤 󰪥 )

icon="${icons[-1]}"
for i in "${!thresholds[@]}"; do
  if (( percent < thresholds[i] )); then
    icon="${icons[$i]}"
    break
  fi
done

emit_tuple 0 "$COLOR_WHITE" "${icon} ${percent}󰏰"
emit_sep
