#!/usr/bin/env bash

# Vars/state already exported from scripts/bar
source "${HOME}/.config/xmobar/scripts/state_loader"

wallpapers_folder="${HOME}/wallpapers"

COM="${HOME}/.config/xmobar/com/wallpaper"
STATE_FILE="${HOME}/.config/xmobar/scripts/state"

if ! command -v nsxiv >/dev/null 2>&1; then
  echo "Warning: nsxiv is not installed or not in PATH."
  exit 1
fi

# Initialize state keys if needed
state_init "wallpaper_lock" 0
state_init "wallpaper_image" ""


# If action is called, re-source state to get current values
if [[ -n "$1" ]]; then
  source "${STATE_FILE}"
fi

case "$1" in
    picker) ${COM}/actions/picker \
      --path=${wallpapers_folder} ;;

    lock_image) ${COM}/actions/lock_image \
      --STATE_FILE=${STATE_FILE}          \
      --LOCK_KEY=wallpaper_lock           \
      --value=${wallpaper_lock}
      # Re-source state after action to get updated value
      source "${STATE_FILE}" ;;

    change) ${COM}/actions/change         \
      --STATE_FILE=${STATE_FILE}          \
      --IMAGE_KEY=wallpaper_image         \
      --selected_image=${wallpaper_image} \
      --is_locked=${wallpaper_lock}
      # Re-source state after action to get updated value
      source "${STATE_FILE}" ;;
    *) ;;
esac

source "${HOME}/.config/xmobar/scripts/page/index" 2

colors=(${COLOR_WHITE} ${COLOR_WARNING})
icon="󰸉"

echo "<fc=${colors[wallpaper_lock]}>${icon}</fc>"
