#!/usr/bin/env bash
# Generated by pywal — do not edit manually
# Sourced by .profile to set xmobar/xmonad color env vars

export XMB_COLOR_WHITE="{color15}"
export XMB_COLOR_MUTE="{color8}"
export XMB_COLOR_INFO="{color6}"
export XMB_COLOR_OK="{color2}"
export XMB_COLOR_WARNING="{color3}"
export XMB_COLOR_CRITIC="{color1}"
export XMB_COLOR_DANGER="{color9}"
export XMB_COLOR_ORANGE="{color11}"

export XOB_NORMAL_FG_BRIGHTNESS="{color3}"
export XOB_NORMAL_BORDER_BRIGHTNESS="{color11}"

export XOB_NORMAL_FG_VOLUME="{color4}"
export XOB_NORMAL_BORDER_VOLUME="{color8}"

export XOB_OF_FG_VOLUME="{color1}"
export XOB_OF_BORDER_VOLUME="{color9}"
