#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --currentIndex=*) currentIndex="${arg#*=}" ;;
    --count=*)        count="${arg#*=}"        ;;
    --STATE_FILE=*)   STATE_FILE="${arg#*=}"   ;;
    --KEY=*)          KEY="${arg#*=}"          ;;
    *) echo "Unknown argument: $arg" ; exit 1  ;;
  esac
done

val=$(( (currentIndex + 1 + ${count}) % ${count} ))

sed -i "s/^$KEY=.*/$KEY=$val/" "$STATE_FILE"
