#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --STATE_FILE=*) STATE_FILE="${arg#*=}" ;;
    --KEY=*) KEY="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

sed -i "s/^$KEY=.*/$KEY=-1/" "$STATE_FILE"
