#!/usr/bin/env bash

COM="${HOME}/.config/xmobar/com/page"
[[ -n "$1" ]] && STATE_FILE="${HOME}/.config/xmobar/scripts/state" && source "${STATE_FILE}"

source "${HOME}/.config/xmobar/scripts/state_loader"
state_init "page_number" 1

case "$1" in
  toggle) ${COM}/actions/toggle \
    --value=${page_number}      \
    --STATE_FILE=${STATE_FILE}  \
    --KEY=page_number ;;
  *) ;;
esac

icon=$([[ $page_number -eq 2 ]] && echo "󰔡" || echo "󰨙")
echo "<fc=${COLOR_WHITE}>${icon}</fc>"
