#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --sink=*)     sink="${arg#*=}" ;;
    --volume=*)   volume="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

wpctl set-mute "${sink}" toggle
echo ${volume}! > "${HOME}/.config/xob/volume/value"

"${HOME}/.config/xmobar/scripts/refresh"
