#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --sink=*)        sink="${arg#*=}" ;;
    --step=*)        step="${arg#*=}" ;;
    --muted=*)       muted="${arg#*=}" ;;
    --volume=*)      volume="${arg#*=}" ;;
    --max_volume=*)  max_volume="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done


if (( muted == 1 )); then
  wpctl set-mute "${sink}" toggle
  wpctl set-volume "${sink}" 10%
  echo 10 > "${HOME}/.config/xob/volume/value"
  exit 0
fi

if (( volume >= max_volume )); then
  wpctl set-volume "${sink}" ${max_volume}%
  echo $max_volume > "${HOME}/.config/xob/volume/value"
else
  wpctl set-volume "${sink}" ${step}%+
  echo $((volume + step)) > "${HOME}/.config/xob/volume/value"
fi

"${HOME}/.config/xmobar/scripts/refresh"
