#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --sink=*)   sink="${arg#*=}" ;;
    --step=*)   step="${arg#*=}" ;;
    --volume=*) volume="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

if (( volume <= 0 )); then
  wpctl set-volume "${sink}" 0%
  echo 0 > "${HOME}/.config/xob/volume/value"
else
  wpctl set-volume "${sink}" ${step}%-
  echo $((volume - step)) > "${HOME}/.config/xob/volume/value"
fi

"${HOME}/.config/xmobar/scripts/refresh"
