#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/env"
source "${BAR_COMPONENTS_DIR}/scripts/check_dependency"
check_dependency "sensors"

COM="${BAR_COMPONENTS_DIR}/com/cpu_temp"
[[ -n "$1" ]] && source "${STATE_FILE}"

source "${BAR_COMPONENTS_DIR}/scripts/cache"
source "${BAR_COMPONENTS_DIR}/scripts/page/index" 2
source "${BAR_COMPONENTS_DIR}/scripts/tuples"

temp=$(cache_cmd "sensors" 3 sensors | awk '/acpitz-acpi-0/ {flag=1} flag && /temp1/ {gsub(/[+°C]/,"",$2); print $2; exit}')
temp_int=${temp%.*}

thresholds=(50 70 85 95)
tempicons=(   "󰈅")
tempcolors=("$COLOR_OK" "$COLOR_WARNING" "$COLOR_DANGER" "$COLOR_CRITIC")
tempcolor="${tempcolors[-1]}"
tempicon="${tempicons[-1]}"

for i in "${!thresholds[@]}"; do
  if (( temp_int < thresholds[i] )); then
    tempcolor="${tempcolors[$i]}"
    tempicon="${tempicons[$i]}"
    break
  fi
done

case "$1" in
  top) ${COM}/actions/htop ;;
  *) ;;
esac

emit_tuple 0 "$tempcolor" "${tempicon} ${temp}°"
emit_sep
