#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/check_dependency"
check_dependency "scrot"
check_dependency "xrandr"
check_dependency "swappy"
check_dependency "xclip"

COM="${HOME}/.config/xmobar/com/screenshot"
[[ -n "$1" ]] && STATE_FILE="${HOME}/.config/xmobar/scripts/state" && source "${STATE_FILE}"

DESTINATION="$HOME/screenshots"

source "${HOME}/.config/xmobar/scripts/state_loader"
state_init "screenshot_edit" 0

case "$1" in
  take) ${COM}/actions/take      \
    --DESTINATION=${DESTINATION} \
    --edit=${screenshot_edit} ;;

  toggle) ${COM}/actions/toggle  \
    --STATE_FILE=${STATE_FILE}   \
    --KEY=screenshot_edit        \
    --value=${screenshot_edit} ;;

  clear) ${COM}/actions/clear \
    --DESTINATION=${DESTINATION} ;;
  *) ;;
esac

source "${HOME}/.config/xmobar/scripts/page/index" 2

color=$([[ $screenshot_edit -eq 0 ]] && echo "${COLOR_WHITE}" || echo "${COLOR_WARNING}")
echo "<fc=${color}>󰹑</fc>"
