#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/env"
source "${BAR_DIR}/scripts/render"

COM="$(resolve_component "screenshot")"

xmobar_actions "$COM" \
  "1:take"            \
  "2:clear"           \
  "3:toggle"
