name : xmonad-config
version : 0.1.0
dependencies :
  - base >= 4.14 && < 5
  - xmonad
  - xmonad-contrib
  - xmobar
  - X11
  - containers

executables :
  xmobar:
    main: /home/void/.config/xmobar/xmobar2.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  xmonadctl :
    main:  xmonadctl.hs
  xmonad :
    main:  xmonad.hs
    ghc-options :
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
