#!/usr/bin/env bash
# xbps-install libspa-bluetooth -- bluetooth support for audio


source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/page/index"
COM="${HOME}/.config/xmobar/com/volume"

STEP=3
MAX_VOLUME=125
ICON_SPEAKER="󰓃"
ICON_HEADPHONES="<fc=${COLOR_INFO}> 󱡬</fc> 󰋋"
ICON_USB_HEADPHONES="<fc=${COLOR_INFO}>  </fc> 󰋋"
ICON_WIRELESS_HEADPHONES="<fc=${COLOR_INFO}> </fc> 󰋋"
ICON_MUTED=""

# ------------------------------

default_sink="@DEFAULT_AUDIO_SINK@"

get_volume() {
  wpctl get-volume "${default_sink}" | awk '{printf "%.0f\n", $2 * 100}'
}

is_muted() {
  wpctl get-volume "${default_sink}" | grep -q MUTED  && echo 1 || echo 0
}

get_sink_icon() {


  INFO="$(wpctl inspect ${default_sink})"

  case "$INFO" in
    *'device.api = "bluez5"'*) echo "${ICON_WIRELESS_HEADPHONES}" ;;
    *'device.bus = "usb"'*) echo "${ICON_USB_HEADPHONES}" ;;

    # Wired headset (jack)
    *'port.name = "analog-output-headphones"'*|\
    *'port.name = "analog-output-headset"'*)
      echo "$ICON_HEADPOHNES" ;;

    * ) echo "${ICON_SPEAKER}" ;;
  esac
}

case "$1" in
    volume_jump)  ${COM}/actions/volume_jump     --sink=${default_sink} --volume=$(get_volume) --muted=$(is_muted) --icon="$(get_sink_icon)" ;;
    volume_up)    ${COM}/actions/volume_up       --sink=${default_sink} --volume=$(get_volume) --muted=$(is_muted) --step=${STEP} --max_volume=${MAX_VOLUME} ;;
    volume_down)  ${COM}/actions/volume_down     --sink=${default_sink} --volume=$(get_volume) --step=${STEP} ;;
    mute)         ${COM}/actions/mute            --sink=${default_sink} --volume=$(get_volume) ;;
    toggle)       ${COM}/actions/cycle_output ;;
esac

if ! pgrep -x wireplumber >/dev/null; then
  echo "<fc=${COLOR_DANGER}>  󰖁</fc>${SEP}"
  exit
fi

if (( $(is_muted) == 1 )); then
  echo "<fc=${COLOR_MUTE}>$ICON_MUTED</fc>${SEP}"
  exit
fi

icon=$(get_sink_icon)
vol=$(get_volume)

thresholds=(0 20 40 75)
sound_icons=("" "" "" "󰕾" "")

sound_icon="${sound_icons[-1]}"


for i in "${!thresholds[@]}"; do
  if (( vol <= thresholds[i] )); then
    sound_icon="${sound_icons[i]}"
    break
  fi
done

output="$sound_icon  $vol󰏰 <fc=${COLOR_MUTE}>󰜥</fc> $icon"
if (( vol > 100 )); then
  echo "<fc=${COLOR_DANGER}>${output}</fc>${SEP}"
else
  echo "${output}${SEP}"
fi
