#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/render"

COM="${HOME}/.config/xmobar/com/volume/index"

xmobar_actions "$COM" \
  "1:volume_jump" \
  "2:mute" \
  "3:toggle" \
  "4:volume_up" \
  "5:volume_down"
