#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"


if ! command -v xset >/dev/null 2>&1; then
  echo "Warning: xset is not installed or not in PATH."
  exit 1
fi

if xset q | grep "Caps Lock: *on" > /dev/null; then
  echo "<fc=${COLOR_WARNING}><fn=1>󰪛</fn> </fc>"
fi
