#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --currentIndex=*) currentIndex="${arg#*=}"           ;;
    --count=*)        count="${arg#*=}"                  ;;
    --STATE_FILE=*)   STATE_FILE="${arg#*=}"             ;;
    --KEY=*)          KEY="${arg#*=}"                    ;;
    *) echo "Unknown argument: $arg" ; exit 1            ;;
  esac
done

source "${HOME}/.config/barlib/scripts/init"
source "${BAR_COMPONENTS_DIR}/scripts/state_loader"
val=$(( (currentIndex - 1 + ${count}) % ${count} ))
state_update "${KEY}" $val
"${REFRESH_CMD}"
