#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --state=*) state="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

power=(on off)
bluetoothctl power "${power[state]}" >/dev/null
