#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --LOADING_KEY=*) LOADING_KEY="${arg#*=}" ;;
    --ISP_KEY=*) ISP_KEY="${arg#*=}" ;;
    --UP_KEY=*) UP_KEY="${arg#*=}" ;;
    --DOWN_KEY=*) DOWN_KEY="${arg#*=}" ;;
    --TIMESTAMP_KEY=*) TIMESTAMP_KEY="${arg#*=}" ;;
    --STATE_FILE=*) STATE_FILE="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

source "${HOME}/.config/xmobar/scripts/state_loader"

state_update "$LOADING_KEY" 1

# Run speedtest in background
(
  COM="${HOME}/.config/xmobar/com/speedtest"

  ${COM}/scripts/runner        \
    --STATE_FILE=${STATE_FILE} \
    --ISP_KEY=${ISP_KEY}       \
    --UP_KEY=${UP_KEY}         \
    --DOWN_KEY=${DOWN_KEY}     \
    --TIMESTAMP_KEY=${TIMESTAMP_KEY}

  source "${HOME}/.config/xmobar/scripts/state"

  ${COM}/actions/show        \
    --isp="${speedtest_isp}" \
    --down=${speedtest_down} \
    --up=${speedtest_up}     \
    --timestamp=${speedtest_timestamp}

  source "${HOME}/.config/xmobar/scripts/state_loader"
  state_update "$LOADING_KEY" 0
) &
