#!/usr/bin/env bash

# Parse named parameters
for arg in "$@"; do
  case $arg in
    --isp=*)       isp="${arg#*=}" ;;
    --down=*)      down="${arg#*=}" ;;
    --up=*)        up="${arg#*=}" ;;
    --timestamp=*) timestamp="${arg#*=}" ;;
    *) echo "Unknown argument: $arg" ; exit 1 ;;
  esac
done

age=$(( $(date +%s) - timestamp ))

if (( age < 60 )); then
  ago="${age}s ago"
elif (( age < 3600 )); then
  ago="$(( age / 60 ))m ago"
else
  ago="$(( age / 3600 ))h ago"
fi

notify-send "$(printf "󰖩  %s\n\n↓ %s Mbits/s\n↑ %s Mbits/s\n(%s)" \
  "$isp" "$down" "$up" "$ago")"
