#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/check_dependency"
check_dependency "nsxiv"

COM="${HOME}/.config/xmobar/com/wallpaper"
[[ -n "$1" ]] && STATE_FILE="${HOME}/.config/xmobar/scripts/state" && source "${STATE_FILE}"

wallpapers_folder="${HOME}/wallpapers"

source "${HOME}/.config/xmobar/scripts/state_loader"
state_init "wallpaper_lock" 0
state_init "wallpaper_image" ""

case "$1" in
    picker) ${COM}/actions/picker \
      --path=${wallpapers_folder} ;;

    lock_image) ${COM}/actions/lock_image \
      --STATE_FILE=${STATE_FILE}          \
      --LOCK_KEY=wallpaper_lock           \
      --value=${wallpaper_lock}           ;;

    change) ${COM}/actions/change         \
      --STATE_FILE=${STATE_FILE}          \
      --IMAGE_KEY=wallpaper_image         \
      --selected_image=${wallpaper_image} \
      --is_locked=${wallpaper_lock}       ;;
    *) ;;
esac

source "${HOME}/.config/xmobar/scripts/page/index" 2

colors=(${COLOR_WHITE} ${COLOR_WARNING})
icon="󰸉"

echo "<fc=${colors[wallpaper_lock]}>${icon}</fc>"
