#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/env"
source "${BAR_DIR}/scripts/render"

COM="$(resolve_component "wallpaper")"

xmobar_actions "$COM" \
  "1:picker"          \
  "2:lock_image"      \
  "3:change"
