#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
source "${BAR_DIR}/scripts/render"

COM="$(resolve_component "volume_output")"

xmobar_actions "$COM" \
  "1:info"            \
  "3:toggle"
