#!/usr/bin/env bash

source "${HOME}/.config/barlib/scripts/init"
source "${BAR_COMPONENTS_DIR}/scripts/check_dependency"
check_dependency "xset" --exit

[[ -n "$1" ]] && source "${STATE_FILE}"


if xset q | grep -q "Caps Lock: *on"; then
  emit_tuple 1 "$COLOR_WARNING" "󰪛"
  emit_sep
fi
