#!/usr/bin/env bash

COM="${HOME}/.config/xmobar/com"

components=(
  "capslock"
  "updates"
  "volume"
  "brightness"
  "bluetooth"
  "battery"
  "cpu_temp"
  "space"
  "network"
  "speedtest"
  "rofi_theme"
  "page"
  "calendar"
  "power"
)

bar=""
for c in "${components[@]}"; do
  bar+="$("$COM/$c/render")"
done

printf '%s\n' "$bar"
