#!/usr/bin/env bash

source "${HOME}/.config/xmobar/scripts/vars"
source "${HOME}/.config/xmobar/scripts/page/index" 1

if ! command -v bluetoothctl >/dev/null 2>&1; then
  echo "Warning: bluetoothctl is not installed or not in PATH."
  exit 1
fi

if ! command -v upower >/dev/null 2>&1; then
  echo "Warning: upower is not installed or not in PATH."
  exit 1
fi

COM="${HOME}/.config/xmobar/com/bluetooth"
LABEL_FILE="${COM}/state/label"
if [ ! -f "$LABEL_FILE" ]; then
  echo -1 > "$LABEL_FILE"
fi

currentIndex=$(< "$LABEL_FILE")

state=$(bluetoothctl show | awk '/Powered/ {print ($2=="yes"?1:0)}')

outputColor="#ffffff"
disabledColor=${COLOR_MUTE}
thresholds=(10 33 66)
timercolors=(${COLOR_CRITIC} ${COLOR_DANGER}  ${COLOR_WARNING} ${COLOR_OK})

mapfile -t connectedDevices < <(
  bluetoothctl devices Connected | sed 's/^Device [A-F0-9:]* //'
)

if ! command -v bluetuith >/dev/null 2>&1; then
  echo "Warning: bluetuith is not installed or not in PATH."
fi

if [ ${#connectedDevices[@]} -eq 0 ]; then
  echo -1 > "$LABEL_FILE"
fi

case "$1" in
    open)     ${COM}/actions/open ;;
    toggle)   ${COM}/actions/toggle --state=${state} ;;
    reset)    ${COM}/actions/reset      --LABEL_FILE=${LABEL_FILE} ;;
    cycle_up) ${COM}/actions/cycle_up   --LABEL_FILE=${LABEL_FILE} --currentIndex=${currentIndex} --connectedDevices=${connectedDevices} ;;
    cycle_down) ${COM}/actions/cycle_up --LABEL_FILE=${LABEL_FILE} --currentIndex=${currentIndex} --connectedDevices=${connectedDevices} ;;
    *) ;;
esac

if [ "$currentIndex" -eq -1 ]; then
  connectedCount=${#connectedDevices[@]}
  label="  ${connectedCount} devices"
  if [ "$connectedCount" -eq 1 ]; then
    label="  ${connectedCount} device"
  elif [ "$connectedCount" -eq 0 ]; then
    label=""
  fi
else
  percentage=$(upower --dump | awk -v name="${connectedDevices[$currentIndex]}" '
      /^ *model:/ {
          # rebuild the model name after the colon
          $1=""; sub(/^ +/, "", $0)
          if ($0 == name) found=1
      }
      found && /percentage:/ {
          gsub("%","",$2)
          print $2
          exit
      }
  ')

  if [[ -z "$percentage" ]]; then
    percentage=100
  fi

  outputColor=${timercolors[${#timercolors[@]}-1]}
  for i in "${!thresholds[@]}"; do
    if (( percentage < thresholds[i] )); then
      outputColor=${timercolors[i]}
      break
    fi
  done
  label="  <fc=${outputColor}>$((currentIndex + 1))/${#connectedDevices[@]} ${connectedDevices[$currentIndex]} $percentage󰏰</fc>"
fi

icons=("󰂲" "󰂰")
colors=(${disabledColor} ${outputColor})

echo "<fc=${colors[$state]}>${icons[$state]}${label}</fc>${SEP}"
